### ISSUE TITLE
Avoid fetching images directly from IIIF-server URL

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/kretschmer-static-py#1]
The URL you are using here 
https://github.com/acdh-oeaw/kretschmer-static-py/blob/856754541447bd428c1b120730a938810c95f3ab/templates/object.html#L254
can change any time

The nice thing though about ARCHE-API is that you can access the IIIF-Endpoint via the ARCHE-Resource ID, either it's handle-id or (more useful) the ARCHE-ID designed by you, the https://id.acdh.oeaw.ac.at/{whatever}

because https://id.acdh.oeaw.ac.at/{whatever}?format=iiif redirects you to the iiif-server, something like https://loris.acdh.oeaw.ac.at/uuid:/{whatever}/full/full/0/default.jpg

https://id.acdh.oeaw.ac.at/auden-musulin-papers/amp_0003.jpg?format=iiif -> https://loris.acdh.oeaw.ac.at/uuid:/auden-musulin-papers/amp_0003.jpg/full/full/0/default.jpg

The good thing using the `?format=iiif` param is that if the underlying IIIF service or its logic changes, your app shouldn't be affected at all

**Comment by linxOD** [comment]
6442f9dd3e5fb4d58fcc8672db56a1286034ed69
